# Generated by Django 3.2.9 on 2021-12-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='listings',
            options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AddField(
            model_name='listings',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listings',
            name='ctg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='listings',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
